tlscommon.c

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

tlscommon.c: removed openssl 1.1 deprecated API

---

tests/t_fticks.c

tests/t_fticks.c uses strcmp, but did not include <string.h>, which at
least in some environments made the build fail.

Add missing #include to tests/t_fticks.c

---

dtls.c
radsecproxy.c
util.c

This fixes compilation on FreeBSD systems, addressing the issue mentioned in #25 plus another one spot where non-portable code was used.
This is untested, but seems to build on both Linux and FreeBSD systems.

Fix compilation on FreeBSD

---

tlscommon.c

The old callback was deprecated in version 1.0.0 of OpenSSL
Fixes compilation without deprecated APIs enabled on 1.0.2.

Switch to OpenSSL's THREADID API

---

radsecproxy.c
util.c
util.h

This should fix issue #37 by moving the include of "sys/time.h" from util.c to util.h and correcting the indentation of the if clause at line 1094 (radsecproxy.c)

 Compilation fails under Alpine Linux

---

rewrite.c

When attempting to compile on FreeBSD, the compiler complains that `htonl` and `ntohl` are implicitly declared. I'm assuming that these are inherited from arpa/inet.h, so just adding the include should fix the problem.

Add arpa/inet.h include because of htonl ntohl

---

dtls.c

When compiling on FreeBSD using libressl, compilation failed because `BIO_ADDR` is an unknown symbol in LibreSSL. I didn't get any new warnings from this change AFAIC.

Do not cast to BIO_ADDR when using LibreSSL

---

radsecproxy.conf.5.in

Fixing a simple spelling error detected by Lintian in Debian.

Fix spelling error

---

radsecproxy.c
radsecproxy.h

GCC 10 compatibility as per https://gcc.gnu.org/gcc-10/porting_to.html

Declare pthread_attr as extern in header (fixes #63)

---

radsecproxy.conf.5.in

The manpage mentions the configuration setting `WhitelistAttrbiute` but it should be `WhitelistAttribute`.

Fix typo in manpage

---

tls.c

To ease some analysis about what entities are using dynamic RADSEC and connecting to our server for eduroam authentication purposes, I've made this small patch to tls.c based on code from cnregexp() at tlscommon.c
The added line says something like the below in the logging:
**tlsservernew: from <192.0.2.1>, host <radsec-edupki>, cert CN <radsec.somenet.pt>**
Please be free to strip the comment before the function added. I've added it just for be explicit and ease the traceability of the change. No explicit credits needed!
hope this contribution is valuable to the community.

Add a log line to identify the cert CN of TLS connections

---

tools/naptr-eduroam.sh
tools/radsec-dynsrv.sh

While patching for today's security advisory, I noticed another issue in the dynamic lookup scripts.
The realm is passed as a command-line argument and then passed unquoted to either dig or host. The shell is sensible enough to prevent me from using this to execute a different command, but I can exploit it to pass options to dig. Consider the difference here:
```
vagrant@eduroam-cpt-01:~$ wget -q https://raw.githubusercontent.com/radsecproxy/radsecproxy/1.9.0/tools/naptr-eduroam.sh && chmod +x naptr-eduroam.sh
vagrant@eduroam-cpt-01:~$ ./naptr-eduroam.sh 'tenet.ac.za'
server dynamic_radsec.tenet.ac.za {
host flr-cpt.eduroam.ac.za:2083
host flr-jnb.eduroam.ac.za:2083
type TLS
}
vagrant@eduroam-cpt-01:~$ ./naptr-eduroam.sh 'tenet.ac.za +domain=tenet.za.net +ndots=10'
server …
```

Prevent realm being interpreted as options in dynamic lookup

---

README

While Fedora EPEL is indeed not the official source for CentOS/RHEL/Rocky Linux, it's likely the most prominent, most used and a very well known third-party repository out there. As a Fedora/EPEL package maintainer my intention is to apply the same quality for EPEL packages like for Fedora packages. The usage of `yum` rather `dnf` is explicitly suggested because CentOS/RHEL 7 is still often used.
P.S.: Minor fix for a typo

Mention how to install radsecproxy on EPEL

---

raddict.h
radmsg.c
radmsg.h
radsecproxy.c
tlv11.c
tlv11.h

This PR will log incoming Accounting-Request packets at log level NOTICE if `AccountingResponse` is set to `on`.
It's a fixed format of logging and only currently supports some RADIUS attributes/values but it's a start!
I'm happy to take suggestions for changes and functionality.

Log incoming accounting packets at NOTICE

---

tls.c

This patch adds the TLS version and the used Cipher Suite to the debug output when a new TLS connection is established.
This is especially useful for finding out which clients use outdated TLS versions for sunsetting older TLS versions.

Include TLS Version and Cipher Suite in debug

---

dtls.c
radsecproxy.c
radsecproxy.conf.5.in
radsecproxy.h
tls.c
tlscommon.c

This PR adds the configuration option `ServerName` in the `client` and `server` sections
The option has the following behavior:
* If set, the certificate name check will check against the value of `ServerName` instead of `Host`
* For server blocks, if SNI is enabled, the value of `ServerName` is used, unless the more specific `SNIservername` is set.
Especially the first behavior is extremely useful in settings where IP addresses are used in the `Host` option to avoid blocking startup due to DNS issues.
With the current setting it is necessary to disable the CertificateNameCheck and provide an own MatchCertificateAttribute with a Regex.
This PR helps with the definition since it does not need to deal with regex and automatically uses both SAN and CN for the check.
(Example for dealing with …

Add ServerName configuration option for certificate name check and SNI

---

udp.c

I found this issue when running the current master with valgrind.
Valgrind message:
Conditional jump or move depends on uninitialised value(s)
The value of `buf` is used in the function `radudpget` (see `udp.c:151`), this value may be uninitialized when creating the pointer in `udpclientrd` (see `udp.c:270`)

Fix uninitialized value (found by valgrind)

---

tlscommon.c

On upgrading radsecproxy from 1.9.1 to 1.9.2, we started seeing an issue where tls clients were reporting a socket timeout on sending a malformed radius packet (with wrong secret) instead of radsecproxy closing the SSL connection (which was the behaviour in 1.9.1). Debugging this, we found an issue in radsecproxy whereby some threads were not exiting (namely `tlsserverwr`) leading to this.
When `radsrv` returns 0 because of radius packet validation failure, `tlsserverrd` does not set any state to indicate to `tlsserverwr` thread that SSL connection with client is closed. It only calls `pthread_cond_signal(&client->replyq->cond);`. `tlsserverwr` thread on receiving the thread conditional signal moves ahead and checks whether SSL is shutdown using `SSL_get_shutdown(client->ssl)` but since …

Shutdown ssl connection with client if radius request packet validation fails

---

dtls.c

If it's DTLS, then the debug message should not be identical to TLS.

Fix debug messages for dtls

---

radmsg.c

* Fix spelling detected by Debian Lintian
* unify the spelling of message-authenticator, making it easier to grep for in the log output

Fix spelling and unify spelling of message-authenticator

---

tlscommon.c

When specifying `DtlsVersion DTLS1:DTLS1_2` in a tls block. there is an error "invalid DtlsVersion DTLS1:DTLS1_2".
TLS versions values are defined in ascending order in Openssl but DTLS versions values are defined in descending order. Therefore, in the mentioned case, `conf_tls_version()` returns false (last comparison):

Dtls version fix master
